"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { apiPost, apiPatch, canMutate } from "@/lib/api/client";
import { useToast } from "@/components/shared/toast";
import { formatCurrency } from "@/lib/format";
import { DollarSign, Loader2 } from "lucide-react";
import type { ValueDeclaration, ValueMethod } from "@/lib/types";

const VALUE_METHODS: { value: ValueMethod; label: string; description: string }[] = [
  { value: "revenue_attribution", label: "Revenue Attribution", description: "Direct or attributed revenue generated by this product" },
  { value: "cost_avoidance", label: "Cost Avoidance", description: "Costs avoided by using this product instead of alternatives" },
  { value: "efficiency_gain", label: "Efficiency Gain", description: "Time or resource savings enabled by this product" },
  { value: "compliance", label: "Compliance Requirement", description: "Regulatory or audit requirement that mandates this product" },
  { value: "strategic", label: "Strategic Enabler", description: "Enables strategic initiatives or competitive advantage" },
];

interface ValueDeclarationDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  productId: string;
  productName: string;
  /** Existing declaration when editing; null when creating new */
  existing: ValueDeclaration | null;
  /** Called after successful save to refresh product data */
  onSuccess: () => void;
}

export function ValueDeclarationDialog({
  open,
  onOpenChange,
  productId,
  productName,
  existing,
  onSuccess,
}: ValueDeclarationDialogProps) {
  const { toastSuccess, toastError } = useToast();
  const isEditing = existing !== null;

  // Form state — initialize from existing if editing
  const [method, setMethod] = useState<ValueMethod>(existing?.method ?? "revenue_attribution");
  const [value, setValue] = useState<string>(existing ? String(existing.value) : "");
  const [basis, setBasis] = useState<string>(existing?.basis ?? "");
  const [submitting, setSubmitting] = useState(false);

  // Reset form when dialog opens with new data
  const handleOpenChange = (isOpen: boolean) => {
    if (isOpen) {
      setMethod(existing?.method ?? "revenue_attribution");
      setValue(existing ? String(existing.value) : "");
      setBasis(existing?.basis ?? "");
    }
    onOpenChange(isOpen);
  };

  const parsedValue = parseFloat(value);
  const isValid = !isNaN(parsedValue) && parsedValue > 0 && basis.trim().length > 0;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!isValid || !canMutate) return;

    setSubmitting(true);
    try {
      const payload = { method, value: parsedValue, basis: basis.trim() };
      if (isEditing) {
        await apiPatch(`/assets/${productId}/value`, payload);
        toastSuccess("Value declaration updated");
      } else {
        await apiPost(`/assets/${productId}/value`, payload);
        toastSuccess("Value declaration created");
      }
      onOpenChange(false);
      onSuccess();
    } catch (err: unknown) {
      toastError(err instanceof Error ? err.message : "Failed to save value declaration");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-[480px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-base">
            <DollarSign className="h-4 w-4 text-emerald-600" />
            {isEditing ? "Edit Value Declaration" : "Declare Value"}
          </DialogTitle>
          <DialogDescription className="text-xs">
            {isEditing
              ? `Update the value declaration for ${productName}. Previous reviewers will need to re-acknowledge.`
              : `Declare the monthly business value of ${productName}. This enables ROI calculations and capital governance.`}
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Value Amount */}
          <div>
            <label htmlFor="vd-value" className="block text-sm font-medium text-gray-700 mb-1.5">
              Monthly Value ($)
            </label>
            <div className="relative">
              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm">$</span>
              <input
                id="vd-value"
                type="number"
                min="1"
                step="any"
                required
                value={value}
                onChange={(e) => setValue(e.target.value)}
                className="w-full rounded-lg border border-gray-200 pl-7 pr-3 py-2.5 text-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                placeholder="e.g. 50000"
              />
            </div>
            {parsedValue > 0 && (
              <p className="text-xs text-gray-400 mt-1">
                {formatCurrency(parsedValue, true)}/month · {formatCurrency(parsedValue * 12, true)}/year
              </p>
            )}
          </div>

          {/* Method */}
          <div>
            <label htmlFor="vd-method" className="block text-sm font-medium text-gray-700 mb-1.5">
              Valuation Method
            </label>
            <select
              id="vd-method"
              value={method}
              onChange={(e) => setMethod(e.target.value as ValueMethod)}
              className="w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              {VALUE_METHODS.map((m) => (
                <option key={m.value} value={m.value}>
                  {m.label}
                </option>
              ))}
            </select>
            <p className="text-xs text-gray-400 mt-1">
              {VALUE_METHODS.find((m) => m.value === method)?.description}
            </p>
          </div>

          {/* Basis */}
          <div>
            <label htmlFor="vd-basis" className="block text-sm font-medium text-gray-700 mb-1.5">
              Value Basis
            </label>
            <textarea
              id="vd-basis"
              required
              value={basis}
              onChange={(e) => setBasis(e.target.value)}
              rows={3}
              maxLength={2000}
              className="w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm placeholder-gray-400 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="Explain how this value was determined. E.g., 'Powers the executive dashboard used by 12 VPs for quarterly planning. Revenue impact estimated at $50K/month based on decision velocity improvements.'"
            />
            <p className="text-xs text-gray-400 mt-1 text-right">
              {basis.length}/2000
            </p>
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="text-xs h-9"
              onClick={() => onOpenChange(false)}
              disabled={submitting}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              size="sm"
              className="text-xs h-9"
              disabled={!isValid || submitting || !canMutate}
            >
              {submitting ? (
                <>
                  <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                  Saving…
                </>
              ) : isEditing ? (
                "Update Declaration"
              ) : (
                "Declare Value"
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
