"""initial_schema

Revision ID: 1974dec37174
Revises: 
Create Date: 2026-02-23 11:22:45.119829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1974dec37174'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_data',
    sa.Column('industry', sa.Enum('retail', 'finance', 'saas', 'healthcare', name='benchmark_industry', create_constraint=True), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('median_roi', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('median_cost_per_consumer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('median_portfolio_roi', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('p25_roi', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('p75_roi', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('business_units',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name')
    )
    op.create_table('connector_configs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.Enum('snowflake', 'databricks', 'bigquery', 'redshift', 'fabric', 'adls', 's3', 'gcs', 'iceberg', 'delta_lake', 'trino', 'presto', 'athena', 'dremio', 'postgresql', 'sql_server', 'mysql', 'oracle', 'mongodb', 'power_bi', 'mock', 'replay', name='connector_type', create_constraint=True), nullable=False),
    sa.Column('credentials', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('connected', 'syncing', 'error', 'disconnected', name='connector_status', create_constraint=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('products_found', sa.Integer(), nullable=False),
    sa.Column('cost_coverage', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('usage_coverage', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_configs_org_id'), 'connector_configs', ['org_id'], unique=False)
    op.create_table('data_products',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('business_unit', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('snowflake', 'databricks', name='platform_type', create_constraint=True), nullable=False),
    sa.Column('lifecycle_stage', sa.Enum('draft', 'active', 'growth', 'mature', 'decline', 'retired', name='lifecycle_stage', create_constraint=True), nullable=False),
    sa.Column('monthly_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('declared_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usage_implied_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('composite_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('roi', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roi_band', sa.Enum('high', 'healthy', 'underperforming', 'critical', name='roi_band', create_constraint=True), nullable=True),
    sa.Column('cost_trend', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('cost_coverage', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('monthly_consumers', sa.Integer(), nullable=False),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('usage_trend', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('peak_consumers', sa.Integer(), nullable=False),
    sa.Column('freshness_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('freshness_sla', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('completeness', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_certified', sa.Boolean(), nullable=False),
    sa.Column('subscription_count', sa.Integer(), nullable=False),
    sa.Column('downstream_products', sa.Integer(), nullable=False),
    sa.Column('downstream_models', sa.Integer(), nullable=False),
    sa.Column('downstream_dashboards', sa.Integer(), nullable=False),
    sa.Column('is_retirement_candidate', sa.Boolean(), nullable=False),
    sa.Column('has_cost_spike', sa.Boolean(), nullable=False),
    sa.Column('has_usage_decline', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_products_org_id'), 'data_products', ['org_id'], unique=False)
    op.create_index(op.f('ix_data_products_owner_id'), 'data_products', ['owner_id'], unique=False)
    op.create_table('policy_configs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('valuation', 'lifecycle', 'cost', 'governance', name='policy_category', create_constraint=True), nullable=False),
    sa.Column('current_value', sa.String(length=255), nullable=False),
    sa.Column('default_value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_configs_org_id'), 'policy_configs', ['org_id'], unique=False)
    op.create_table('portfolio_monthly',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('total_products', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('average_roi', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_consumers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'month')
    )
    op.create_table('connector_runs',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='run_status', create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_runs_connector_id'), 'connector_runs', ['connector_id'], unique=False)
    op.create_table('cost_breakdowns',
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('compute', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('storage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pipeline', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('human_estimate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id')
    )
    op.create_table('cost_monthly',
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('compute', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('storage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pipeline', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('human_estimate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coverage_pct', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id', 'month')
    )
    op.create_index(op.f('ix_cost_monthly_data_product_id'), 'cost_monthly', ['data_product_id'], unique=False)
    op.create_table('data_product_dependencies',
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.Enum('data_product', 'model', 'dashboard', name='dependency_type', create_constraint=True), nullable=False),
    sa.Column('dependency_name', sa.String(length=255), nullable=False),
    sa.Column('dependency_ref', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_product_dependencies_data_product_id'), 'data_product_dependencies', ['data_product_id'], unique=False)
    op.create_table('data_product_tags',
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id', 'tag')
    )
    op.create_table('decisions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('retirement', 'cost_investigation', 'value_revalidation', 'low_roi_review', name='decision_type', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('under_review', 'approved', 'rejected', name='decision_status', create_constraint=True), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('initiated_by', sa.String(length=255), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('assigned_to_title', sa.String(length=255), nullable=True),
    sa.Column('estimated_impact', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_impact', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('impact_basis', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_org_id'), 'decisions', ['org_id'], unique=False)
    op.create_index(op.f('ix_decisions_product_id'), 'decisions', ['product_id'], unique=False)
    op.create_table('marketplace_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('cost_spike', 'usage_drop', 'value_expiring', 'lifecycle_change', 'retirement_candidate', name='notification_type', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['data_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_table('roi_monthly',
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('roi', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('composite_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id', 'month')
    )
    op.create_index(op.f('ix_roi_monthly_data_product_id'), 'roi_monthly', ['data_product_id'], unique=False)
    op.create_table('source_assets',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('asset_name', sa.String(length=512), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'external_id')
    )
    op.create_table('teams',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name')
    )
    op.create_table('usage_monthly',
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('consumers', sa.Integer(), nullable=False),
    sa.Column('queries', sa.Integer(), nullable=False),
    sa.Column('bytes_scanned', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id', 'month')
    )
    op.create_index(op.f('ix_usage_monthly_data_product_id'), 'usage_monthly', ['data_product_id'], unique=False)
    op.create_table('value_declaration_versions',
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('declared_by', sa.String(length=255), nullable=False),
    sa.Column('declared_by_title', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('revenue_attribution', 'cost_avoidance', 'efficiency_gain', 'compliance', 'strategic', name='value_method', create_constraint=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('declared_at', sa.Date(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id', 'version')
    )
    op.create_index(op.f('ix_value_declaration_versions_data_product_id'), 'value_declaration_versions', ['data_product_id'], unique=False)
    op.create_table('value_declarations',
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('declared_by', sa.String(length=255), nullable=False),
    sa.Column('declared_by_title', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('revenue_attribution', 'cost_avoidance', 'efficiency_gain', 'compliance', 'strategic', name='value_method', create_constraint=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('declared_at', sa.Date(), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=False),
    sa.Column('is_expiring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id')
    )
    op.create_table('asset_mappings',
    sa.Column('source_asset_id', sa.UUID(), nullable=False),
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['source_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'data_product_id')
    )
    op.create_table('consumer_teams',
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('consumers', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id', 'team_name')
    )
    op.create_index(op.f('ix_consumer_teams_data_product_id'), 'consumer_teams', ['data_product_id'], unique=False)
    op.create_table('cost_events',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('source_asset_id', sa.UUID(), nullable=True),
    sa.Column('cost_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['source_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_events_connector_id'), 'cost_events', ['connector_id'], unique=False)
    op.create_index(op.f('ix_cost_events_period_start'), 'cost_events', ['period_start'], unique=False)
    op.create_table('usage_events',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('source_asset_id', sa.UUID(), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=True),
    sa.Column('team_identifier', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bytes_scanned', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['source_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_connector_id'), 'usage_events', ['connector_id'], unique=False)
    op.create_index(op.f('ix_usage_events_event_at'), 'usage_events', ['event_at'], unique=False)
    op.create_table('user_org_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('cfo', 'cdo', 'product_owner', 'consumer', 'admin', name='user_role', create_constraint=True), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', 'role')
    )
    op.create_index(op.f('ix_user_org_roles_org_id'), 'user_org_roles', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_org_roles_user_id'), 'user_org_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_org_roles_user_id'), table_name='user_org_roles')
    op.drop_index(op.f('ix_user_org_roles_org_id'), table_name='user_org_roles')
    op.drop_table('user_org_roles')
    op.drop_index(op.f('ix_usage_events_event_at'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_connector_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_cost_events_period_start'), table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_connector_id'), table_name='cost_events')
    op.drop_table('cost_events')
    op.drop_index(op.f('ix_consumer_teams_data_product_id'), table_name='consumer_teams')
    op.drop_table('consumer_teams')
    op.drop_table('asset_mappings')
    op.drop_table('value_declarations')
    op.drop_index(op.f('ix_value_declaration_versions_data_product_id'), table_name='value_declaration_versions')
    op.drop_table('value_declaration_versions')
    op.drop_index(op.f('ix_usage_monthly_data_product_id'), table_name='usage_monthly')
    op.drop_table('usage_monthly')
    op.drop_table('teams')
    op.drop_table('source_assets')
    op.drop_index(op.f('ix_roi_monthly_data_product_id'), table_name='roi_monthly')
    op.drop_table('roi_monthly')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('marketplace_subscriptions')
    op.drop_index(op.f('ix_decisions_product_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_org_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('data_product_tags')
    op.drop_index(op.f('ix_data_product_dependencies_data_product_id'), table_name='data_product_dependencies')
    op.drop_table('data_product_dependencies')
    op.drop_index(op.f('ix_cost_monthly_data_product_id'), table_name='cost_monthly')
    op.drop_table('cost_monthly')
    op.drop_table('cost_breakdowns')
    op.drop_index(op.f('ix_connector_runs_connector_id'), table_name='connector_runs')
    op.drop_table('connector_runs')
    op.drop_table('portfolio_monthly')
    op.drop_index(op.f('ix_policy_configs_org_id'), table_name='policy_configs')
    op.drop_table('policy_configs')
    op.drop_index(op.f('ix_data_products_owner_id'), table_name='data_products')
    op.drop_index(op.f('ix_data_products_org_id'), table_name='data_products')
    op.drop_table('data_products')
    op.drop_index(op.f('ix_connector_configs_org_id'), table_name='connector_configs')
    op.drop_table('connector_configs')
    op.drop_table('business_units')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('benchmark_data')
    # ### end Alembic commands ###
