"""add_connector_run_event_counts

Revision ID: 9db6c6af1729
Revises: 1974dec37174
Create Date: 2026-02-23 11:35:35.505381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db6c6af1729'
down_revision: Union[str, None] = '1974dec37174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector_runs', sa.Column('usage_events_found', sa.Integer(), nullable=False))
    op.add_column('connector_runs', sa.Column('cost_events_found', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connector_runs', 'cost_events_found')
    op.drop_column('connector_runs', 'usage_events_found')
    # ### end Alembic commands ###
